site_name: PyTorch中文文档
pages:
- [index.md, 主页]
- [notes/autograd.md, '说明', '自动求导机制']
- [notes/cuda.md, '说明', 'CUDA语义']
- [notes/extending.md, '说明', '扩展PyTorch']
- [notes/multiprocessing.md, '说明', '多进程最佳实践']
- [notes/serialization.md, '说明', '序列化语义']
- [package_references/Storage.md, 'PACKAGE参考', 'torch.Storage']
- [package_references/torch-autograd.md, 'PACKAGE参考', 'torch.nn.init']
- [package_references/nn_init.md, 'PACKAGE参考', 'torch.autograd']
- [package_references/legacy.md, 'PACKAGE参考', 'torch.legacy']
- [package_references/torch-cuda.md, 'PACKAGE参考', 'torch.cuda']
- [package_references/ffi.md, 'PACKAGE参考', 'torch.utils.ffi']
- [package_references/model_zoo.md, 'PACKAGE参考', 'torch.utils.model_zoo']
- [package_references/data.md, 'PACKAGE参考', 'torch.utils.data']
- [package_references/Storage.md, 'PACKAGE参考', 'torch.Storage']
- [package_references/nn_init.md, 'PACKAGE参考', 'torch.nn.init']
- [package_references/nn.md, 'PACKAGE参考', 'torch.nn']
- [torchvision/torchvision.md, 'TORCHVISION参考', 'torchvision']
- [torchvision/torchvision-datasets.md, 'TORCHVISION参考', 'torchvision.datasets']
- [torchvision/torchvision-models.md, 'TORCHVISION参考', 'torchvision.models']
- [torchvision/torchvision-transform.md, 'TORCHVISION参考', 'torchvision.transforms']
- [torchvision/torchvision-utils.md, 'TORCHVISION参考', 'torchvision.utils']
- [acknowledgement.md, '致谢']

theme: readthedocs

extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','js/mathjaxhelper.js']
